export const data = [
    {
        "id": 12706935,
        "ast": 2,
        "blk": 1,
        "dreb": 0,
        "fg3_pct": 0.143,
        "fg3a": 7,
        "fg3m": 1,
        "fg_pct": 0.438,
        "fga": 16,
        "fgm": 7,
        "ft_pct": 0.667,
        "fta": 6,
        "ftm": 4,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "36",
        "oreb": 2,
        "pf": 6,
        "player": {
            "id": 666541,
            "first_name": "Luguentz",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Dort",
            "position": "G",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 19,
        "reb": 2,
        "stl": 0,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 0
    },
    {
        "id": 12706936,
        "ast": 1,
        "blk": 0,
        "dreb": 1,
        "fg3_pct": 0.0,
        "fg3a": 1,
        "fg3m": 0,
        "fg_pct": 0.0,
        "fga": 2,
        "fgm": 0,
        "ft_pct": 0.0,
        "fta": 0,
        "ftm": 0,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "16",
        "oreb": 3,
        "pf": 1,
        "player": {
            "id": 17896021,
            "first_name": "Jeremiah",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Robinson-Earl",
            "position": "F",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 0,
        "reb": 4,
        "stl": 0,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 1
    },
    {
        "id": 12706938,
        "ast": 7,
        "blk": 0,
        "dreb": 3,
        "fg3_pct": 0.6,
        "fg3a": 5,
        "fg3m": 3,
        "fg_pct": 0.529,
        "fga": 17,
        "fgm": 9,
        "ft_pct": 0.75,
        "fta": 4,
        "ftm": 3,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "34",
        "oreb": 1,
        "pf": 2,
        "player": {
            "id": 38017703,
            "first_name": "Jalen",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Williams",
            "position": "G-F",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 24,
        "reb": 4,
        "stl": 2,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 2
    },
    {
        "id": 12706939,
        "ast": 11,
        "blk": 0,
        "dreb": 7,
        "fg3_pct": 0.25,
        "fg3a": 4,
        "fg3m": 1,
        "fg_pct": 0.588,
        "fga": 17,
        "fgm": 10,
        "ft_pct": 0.333,
        "fta": 3,
        "ftm": 1,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "34",
        "oreb": 2,
        "pf": 1,
        "player": {
            "id": 17896065,
            "first_name": "Josh",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Giddey",
            "position": "G",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 22,
        "reb": 9,
        "stl": 0,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 4
    },
    {
        "id": 12706940,
        "ast": 3,
        "blk": 0,
        "dreb": 2,
        "fg3_pct": 0.333,
        "fg3a": 9,
        "fg3m": 3,
        "fg_pct": 0.455,
        "fga": 11,
        "fgm": 5,
        "ft_pct": 1.0,
        "fta": 2,
        "ftm": 2,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "29",
        "oreb": 0,
        "pf": 5,
        "player": {
            "id": 3547272,
            "first_name": "Isaiah",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Joe",
            "position": "G",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 15,
        "reb": 2,
        "stl": 1,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 1
    },
    {
        "id": 12706941,
        "ast": 2,
        "blk": 0,
        "dreb": 2,
        "fg3_pct": 0.0,
        "fg3a": 2,
        "fg3m": 0,
        "fg_pct": 0.333,
        "fga": 3,
        "fgm": 1,
        "ft_pct": 1.0,
        "fta": 2,
        "ftm": 2,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "9",
        "oreb": 0,
        "pf": 1,
        "player": {
            "id": 17896036,
            "first_name": "Tre",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Mann",
            "position": "G",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 4,
        "reb": 2,
        "stl": 1,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 0
    },
    {
        "id": 12706942,
        "ast": 0,
        "blk": 0,
        "dreb": 2,
        "fg3_pct": 0.5,
        "fg3a": 2,
        "fg3m": 1,
        "fg_pct": 0.833,
        "fga": 6,
        "fgm": 5,
        "ft_pct": 0.667,
        "fta": 3,
        "ftm": 2,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "15",
        "oreb": 0,
        "pf": 3,
        "player": {
            "id": 407,
            "first_name": "Dario",
            "height_feet": 6,
            "height_inches": 10,
            "last_name": "Saric",
            "position": "F",
            "team_id": 21,
            "weight_pounds": 223
        },
        "pts": 13,
        "reb": 2,
        "stl": 0,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 1
    },
    {
        "id": 12706943,
        "ast": 0,
        "blk": 0,
        "dreb": 0,
        "fg3_pct": 0.0,
        "fg3a": 0,
        "fg3m": 0,
        "fg_pct": 0.0,
        "fga": 0,
        "fgm": 0,
        "ft_pct": 0.0,
        "fta": 0,
        "ftm": 0,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "00",
        "oreb": 0,
        "pf": 0,
        "player": {
            "id": 24572055,
            "first_name": "Olivier",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Sarr",
            "position": "C",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 0,
        "reb": 0,
        "stl": 0,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 0
    },
    {
        "id": 12706944,
        "ast": 1,
        "blk": 1,
        "dreb": 1,
        "fg3_pct": 0.4,
        "fg3a": 5,
        "fg3m": 2,
        "fg_pct": 0.4,
        "fga": 5,
        "fgm": 2,
        "ft_pct": 1.0,
        "fta": 2,
        "ftm": 2,
        "game": {
            "id": 858292,
            "date": "2023-03-01T00:00:00.000Z",
            "home_team_id": 21,
            "home_team_score": 117,
            "period": 4,
            "postseason": false,
            "season": 2022,
            "status": "Final",
            "time": "Final",
            "visitor_team_id": 14,
            "visitor_team_score": 123
        },
        "min": "18",
        "oreb": 0,
        "pf": 4,
        "player": {
            "id": 27924547,
            "first_name": "Lindy",
            "height_feet": null,
            "height_inches": null,
            "last_name": "Waters III",
            "position": "F",
            "team_id": 21,
            "weight_pounds": null
        },
        "pts": 8,
        "reb": 1,
        "stl": 1,
        "team": {
            "id": 21,
            "abbreviation": "OKC",
            "city": "Oklahoma City",
            "conference": "West",
            "division": "Northwest",
            "full_name": "Oklahoma City Thunder",
            "name": "Thunder"
        },
        "turnover": 0
    },
  ]

  export const images = {
    image: 'https://cdn.nba.com/headshots/nba/latest/260x190/1630173.png'
  }
